name: Main Flow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - run: dotnet build GitHubWorkFlow.sln --configuration release

      - run: dotnet publish --configuration release

      - uses: microsoft/variable-substitution@v1
        with:
          files: "${{env.DOTNET_ROOT}}/src/GitHubWorkFlow.Host/appsettings.json"
        env:
          ConnectionStrings.ip: ${{ secret.ip }}

      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy deploy/app.yaml
