name: Main Flow

on:
  branches:
    - master

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - run: dotnet build <my project>
