name: Cloud Run Node Flow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: auth configure-docker && gcloud builds submit --config build-node.yml && gcloud run deploy githubworkflow-nodets --image gcr.io/${{secrets.GCLOUD_PROJECT_ID}}/node --platform managed --region europe-north1 --allow-unauthenticated
